apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dummy-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dummy-app
  template:
    metadata:
      labels:
        app: my-dummy-app
    spec:
      containers:
      - name: my-dummy-app
        image: shaan2212/my-dummy-app-repo:latest
        ports:
        - containerPort: 80

